name: oioubl-schematron-build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Compile schematron assemblies
        shell: pwsh
        run: ./compile.ps1

      - name: Upload build results
        uses: actions/upload-artifact@v2
        with:
         path: '**\*.dll'
