name: oioubl-schematron-release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

env:
  PACKAGES_USER: '${{ github.actor }}'
#  PACKAGES_TOKEN: '${{secrets.GH_PACKAGES_TOKEN}}'

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Compile schematron assemblies
        shell: pwsh
        run: ./compile.ps1

      - name: Nuget pack 
        run: nuget pack **/*.nuspec

      - name: Upload build results
        uses: actions/upload-artifact@v2
        with:
         path: |
                '**\*.dll'
                '**\*.nupkg'

#      - name: Push package
#        run: dotnet nuget push *.nupkg -k ${{secrets.GH_PACKAGES_TOKEN}} -s ${{env.NUGET_SOURCE_URL}}

