name: oioubl-schematron-release

on:
  workflow_dispatch:

env:
  PACKAGES_USER: '${{ github.actor }}'
  FULL_NUSPEC_PATH: './full/OioUbl.Schematron.dll.nuspec'
  SIMPLEINVOICE_NUSPEC_PATH: './simpleinvoice/OioUbl.Schematron.SimpleInvoice.dll.nuspec'
  NUGET_SOURCE_URL: 'https://api.nuget.org/v3/index.json'
  
jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Compile schematron assemblies
        shell: pwsh
        run: ./compile.ps1

      - name: Set version environment variable
        shell: pwsh
        run: ./write-version-variable.ps1

      - name: Nuget pack full
        run: nuget pack ${{env.FULL_NUSPEC_PATH}} -Version ${{env.NUGET_PACKAGE_VERSION}}

      - name: Nuget pack simpleinvoice
        run: nuget pack ${{env.SIMPLEINVOICE_NUSPEC_PATH}} -Version ${{env.NUGET_PACKAGE_VERSION}}

      - name: Upload build results
        uses: actions/upload-artifact@v2
        with:
         path: |
                **\*.dll
                **\*.nupkg

      - name: Push packages
        run: dotnet nuget push *.nupkg --api-key ${{secrets.GH_PACKAGES_TOKEN}} --source ${{env.NUGET_SOURCE_URL}}

